//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlConverter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlConverter.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL entered contain invalid single quotes, make sure the single quotes you are using are not formatted..
        /// </summary>
        internal static string ContainsInvalidSingleQuote {
            get {
                return ResourceManager.GetString("ContainsInvalidSingleQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Error converting SQL; only Update/Delete/Merge code is supported:.
        /// </summary>
        internal static string ConversionUnsuccessful {
            get {
                return ResourceManager.GetString("ConversionUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool will convert any Update, Delete, or Merge SQL code to a select statement, while partially validating the SQL code. Results will update in real-time as you type or add your code into the SQL box. Once the code is converted, you can either highlight the code and copy (CTRL +A) or use the &quot;Copy&quot; button to copy the converted code into your clipboard.
        /// </summary>
        internal static string DefaultRequirements {
            get {
                return ResourceManager.GetString("DefaultRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The below Delete contains an error in the &quot;delete from ...  where&quot; region.
        /// </summary>
        internal static string Delete_Invalid {
            get {
                return ResourceManager.GetString("Delete_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data entered into the SQL box could not be converted.
        /// </summary>
        internal static string InvalidSQLEntry {
            get {
                return ResourceManager.GetString("InvalidSQLEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The below Merge contains an error in the &quot;merge into ... using ...&quot; region.
        /// </summary>
        internal static string Merge_Invalid {
            get {
                return ResourceManager.GetString("Merge_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The below Merge contains an error in the match clause.
        /// </summary>
        internal static string Merge_InvalidMatchedClause {
            get {
                return ResourceManager.GetString("Merge_InvalidMatchedClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an MP Number (Enter any key if the code applies to multiple entities).
        /// </summary>
        internal static string MpRequired {
            get {
                return ResourceManager.GetString("MpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End your SQL statements with a semicolon.
        /// </summary>
        internal static string NoSemicolon {
            get {
                return ResourceManager.GetString("NoSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The below {0} was not converted due to a code error:.
        /// </summary>
        internal static string NotConverted {
            get {
                return ResourceManager.GetString("NotConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Update/Delete/Merge in the SQL box.
        /// </summary>
        internal static string SQLRequired {
            get {
                return ResourceManager.GetString("SQLRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements:.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. An Update/Delete/Merge and MP Number..
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Multiple statements are supported..
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Each piece of SQL code needs to end in a semicolon for the converter to pickup the code..
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to enter a valid SQL statement, ending in a semicolon.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Successfully converted from {0} to:.
        /// </summary>
        internal static string SuccessfullyConverted {
            get {
                return ResourceManager.GetString("SuccessfullyConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The below code entered caused a converter timeout and is causing an error, send this code as feedback to fix the issue in the future:.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The below Update contains an error in the &quot;set&quot; region or in the &quot;set&quot; fields.
        /// </summary>
        internal static string Update_InvalidSet {
            get {
                return ResourceManager.GetString("Update_InvalidSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The below Update contains an error in the &quot;update ... set&quot; region.
        /// </summary>
        internal static string Update_InvalidUpdate {
            get {
                return ResourceManager.GetString("Update_InvalidUpdate", resourceCulture);
            }
        }
    }
}
